package GUI;

import java.sql.SQLException;
import nightsaway_final.DatabaseManager;

/**
 *
 * @author Mr S Malinga (218021100)
 */
public class RoomList extends javax.swing.JFrame {

    /**
     * Creates new form Room1
     */
    public RoomList() {
        initComponents();
    }
    
    public RoomList(String currMonth, int RoomNo)  {
        initComponents();
        tblDetails.setModel((DatabaseManager.getRoomData(currMonth, RoomNo)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jRoom1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnExcursions = new javax.swing.JButton();
        deleteGuest = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(450, 450));
        setMinimumSize(new java.awt.Dimension(450, 450));
        setPreferredSize(new java.awt.Dimension(450, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRoom1.setBackground(new java.awt.Color(255, 255, 255));
        jRoom1.setMaximumSize(new java.awt.Dimension(610, 440));
        jRoom1.setMinimumSize(new java.awt.Dimension(610, 440));
        jRoom1.setName(""); // NOI18N
        jRoom1.setPreferredSize(new java.awt.Dimension(610, 440));
        jRoom1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(610, 440));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(610, 440));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(610, 440));

        tblDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        tblDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDetails.setDropMode(javax.swing.DropMode.INSERT_COLS);
        tblDetails.setMaximumSize(new java.awt.Dimension(300, 64));
        tblDetails.setMinimumSize(new java.awt.Dimension(300, 64));
        tblDetails.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDetails.setShowHorizontalLines(false);
        tblDetails.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblDetails);

        jRoom1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 440, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Sub-logo.PNG"))); // NOI18N
        jRoom1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 130));

        jPanel2.setBackground(new java.awt.Color(215, 236, 251));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_bed_64px.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/icons8_pillow_64px.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jRoom1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 150, 130));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        jRoom1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 70, 30));

        btnExcursions.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExcursions.setText("Book excursions");
        btnExcursions.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnExcursionsActionPerformed(evt);
            }
        });
        jRoom1.add(btnExcursions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, 30));

        deleteGuest.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteGuest.setText("Delete guest");
        deleteGuest.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                deleteGuestActionPerformed(evt);
            }
        });
        jRoom1.add(deleteGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 160, 30));

        getContentPane().add(jRoom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcursionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcursionsActionPerformed
        new ExcursionsPage().setVisible(true);
    }//GEN-LAST:event_btnExcursionsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGuestActionPerformed
        int currRow = tblDetails.getSelectedRow();
        String GuestID = "" + tblDetails.getModel().getValueAt(currRow, 0);
        DatabaseManager.deleteGuest(GuestID);
    }//GEN-LAST:event_deleteGuestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcursions;
    private javax.swing.JButton deleteGuest;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jRoom1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDetails;
    // End of variables declaration//GEN-END:variables
}
